//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TriaCulturaDesktopApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class author
    {
        public author()
        {
            this.emails = new HashSet<email>();
            this.phones = new HashSet<phone>();
            this.projects = new HashSet<project>();
            this.disciplines = new HashSet<discipline>();
        }
    
        public string dni { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public string address { get; set; }
        public virtual string nomComplert { get { return name + " " + surname; } set { } }

    
        public virtual ICollection<email> emails { get; set; }
        public virtual ICollection<phone> phones { get; set; }
        public virtual ICollection<project> projects { get; set; }
        public virtual ICollection<discipline> disciplines { get; set; }
    }
}
