//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TriaCulturaDesktopApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class capacity
    {
        public capacity()
        {
            this.places = new HashSet<place>();
        }
    
        public int id_capacity { get; set; }
        public string type_spectacle { get; set; }
        public int vol_expo { get; set; }
    
        public virtual ICollection<place> places { get; set; }
    }
}
