//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TriaCulturaDesktopApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class capacity
    {
        public capacity()
        {
            this.place_has_capacity = new HashSet<place_has_capacity>();
        }
    
        public int id_capacity { get; set; }
        public string type_spectacle { get; set; }
    
        public virtual ICollection<place_has_capacity> place_has_capacity { get; set; }
    }
}
