//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TriaCulturaDesktopApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class place
    {
        public place()
        {
            this.events = new HashSet<@event>();
            this.requests = new HashSet<request>();
            this.capacities = new HashSet<capacity>();
        }
    
        public int id_place { get; set; }
        public string name { get; set; }
        public int capacity { get; set; }
        public string address { get; set; }
    
        public virtual ICollection<@event> events { get; set; }
        public virtual ICollection<request> requests { get; set; }
        public virtual ICollection<capacity> capacities { get; set; }
    }
}
