//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TriaCulturaDesktopApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class place_has_capacity
    {
        public int capacity_id { get; set; }
        public int place_id { get; set; }
        public Nullable<int> vol_capacity { get; set; }
        public Nullable<decimal> fee { get; set; }
    
        public virtual capacity capacity { get; set; }
        public virtual place place { get; set; }
    }
}
