//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TriaCulturaDesktopApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class project
    {
        public project()
        {
            this.files = new HashSet<file>();
            this.requests = new HashSet<request>();
            this.types = new HashSet<type>();
        }
    
        public int id_project { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public string topic { get; set; }
        public string author_dni { get; set; }
    
        public virtual author author { get; set; }
        public virtual ICollection<file> files { get; set; }
        public virtual ICollection<request> requests { get; set; }
        public virtual ICollection<type> types { get; set; }
    }
}
