//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TriaCulturaDesktopApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class request
    {
        public int id_request { get; set; }
        public Nullable<int> project_id { get; set; }
        public Nullable<int> place_id { get; set; }
        public Nullable<int> is_winner { get; set; }
        public Nullable<System.DateTime> proposed_date { get; set; }
    
        public virtual place place { get; set; }
        public virtual project project { get; set; }
    }
}
