//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TriaCulturaDesktopApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class type
    {
        public type()
        {
            this.projects = new HashSet<project>();
        }
    
        public int id_type { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<project> projects { get; set; }
    }
}
